version: '3'

networks:
  mg_local_network:
    external:
      name: mg_local_network

services:
  academy-database:
    container_name: academy-database
    image: mariadb/server:10.5
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      - MYSQL_DATABASE=${DOCKER_DATABASE_NAME:-academy}
      - MYSQL_USER=${DOCKER_DATABASE_USER:-academy}
      - MYSQL_PASSWORD=${DOCKER_DATABASE_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DOCKER_DATABASE_ROOT_PASSWORD:-dev}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:delegated
    ports:
      - "${DOCKER_DATABASE_PORT:-3406}:3306"
    networks:
      - mg_local_network

  academy-php-fpm:
    container_name: academy-php-fpm
    build:
      context: ./docker/php-fpm/
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - mg_local_network

  academy-nginx:
    image: nginx:1.19
    container_name: academy-nginx
    ports:
      - "${HH_NGINX_PORT:-8085}:80"
    depends_on:
      - academy-php-fpm
    volumes:
      - ./docker/nginx/base/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/base/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html:cached
    networks:
      - mg_local_network


